# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astar.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'astar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61star.proto\x12\x0b\x61star.proto\",\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\"6\n\x04\x45\x64ge\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\t\x12\r\n\x05to_id\x18\x02 \x01(\t\x12\x0e\n\x06weight\x18\x03 \x01(\x01\"d\n\x0cGraphRequest\x12\x10\n\x08graph_id\x18\x01 \x01(\t\x12 \n\x05nodes\x18\x02 \x03(\x0b\x32\x11.astar.proto.Node\x12 \n\x05\x65\x64ges\x18\x03 \x03(\x0b\x32\x11.astar.proto.Edge\"1\n\rStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"T\n\x0cSolveRequest\x12\x10\n\x08graph_id\x18\x01 \x01(\t\x12\x10\n\x08start_id\x18\x02 \x01(\t\x12\x0f\n\x07goal_id\x18\x03 \x01(\t\x12\x0f\n\x07use_asm\x18\x04 \x01(\x08\"X\n\rSolveResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x03(\t\x12\x12\n\ntotal_cost\x18\x03 \x01(\x01\x12\x16\n\x0enodes_explored\x18\x04 \x01(\x04\x32\x93\x01\n\x0c\x41StarService\x12\x43\n\nStoreGraph\x12\x19.astar.proto.GraphRequest\x1a\x1a.astar.proto.StoreResponse\x12>\n\x05Solve\x12\x19.astar.proto.SolveRequest\x1a\x1a.astar.proto.SolveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODE']._serialized_start=28
  _globals['_NODE']._serialized_end=72
  _globals['_EDGE']._serialized_start=74
  _globals['_EDGE']._serialized_end=128
  _globals['_GRAPHREQUEST']._serialized_start=130
  _globals['_GRAPHREQUEST']._serialized_end=230
  _globals['_STORERESPONSE']._serialized_start=232
  _globals['_STORERESPONSE']._serialized_end=281
  _globals['_SOLVEREQUEST']._serialized_start=283
  _globals['_SOLVEREQUEST']._serialized_end=367
  _globals['_SOLVERESPONSE']._serialized_start=369
  _globals['_SOLVERESPONSE']._serialized_end=457
  _globals['_ASTARSERVICE']._serialized_start=460
  _globals['_ASTARSERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
